### ISSUE TITLE
格挡崩溃bug

### ISSUE THREAD

**Issue by latiaotiao** [Cyber2049/Epic-Fight---Indestructible#17]
Weapons of Miracles的折磨巨斧，攻击格挡中的生物，生物耐力降到0的时候100%崩溃。只有这个武器会崩溃，其他的都没问题。模组都是最新的。

**Comment by latiaotiao** [comment]
Description: Ticking player

java.lang.ClassCastException: class yesman.epicfight.gameasset.Animations$1 cannot be cast to class yesman.epicfight.api.animation.types.AttackAnimation (yesman.epicfight.gameasset.Animations$1 and yesman.epicfight.api.animation.types.AttackAnimation are in module epicfight@20.9.2 of loader 'TRANSFORMER' @2bd8c8f1)
	at reascer.wom.skill.weaponpassive.TormentPassiveSkill.lambda$onInitiate$3(TormentPassiveSkill.java:93) ~[WeaponsOfMiracles-20.1.8.5.2.jar%23673!/:20.1.8.5.2] {re:classloading}
	at yesman.epicfight.world.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:22) ~[epicfight-forge-20.9.2-1.20.1.jar%23511!/:20.9.2] {re:classloading}
	at yesman.epicfight.world.entity.eventlistener.PlayerEventListener.triggerEvents(PlayerEventListener.java:73) ~[epicfight-forge-20.9.2-1.20.1.jar%23511!/:20.9.2] {re:classloading}
	at yesman.epicfight.events.EntityEvents.damageEvent(EntityEvents.java:320) ~[epicfight-forge-20.9.2-1.20.1.jar%23511!/:20.9.2] {re:classloading}
	at yesman.epicfight.events.__EntityEvents_damageEvent_LivingDamageEvent.invoke(.dynamic) ~[epicfight-forge-20.9.2-1.20.1.jar%23511!/:20.9.2] {re:classloading,pl:eventbus:B}

**Comment by Cyber2049** [comment]
发个完整的crash-report给我再发一份完整的给wom的作者，从这边没看出是我mod导致的

**Comment by latiaotiao** [comment]
[crash-2024-10-07_20.00.55-server.txt](https://github.com/user-attachments/files/17278084/crash-2024-10-07_20.00.55-server.txt)
我也觉得是wom的问题，但是wom没有github页面了，我在dc上私信过Reascer了，也不知道会不会看。另外我测了玩家pvp不会崩，就是生物格挡破防100%崩溃。像我描述的那样，这个是很常见的崩溃情景了，必然崩溃。
